# Generated by Django 3.0.1 on 2021-03-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210303_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelledapproval',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='cancelledapproval',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
