# Generated by Django 3.0.1 on 2021-03-01 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cancelledapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelledapproval',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='orders.CancelledOrder'),
        ),
    ]
