# Generated by Django 3.0.1 on 2021-03-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210303_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancelledapproval',
            name='refund_amount',
        ),
    ]
