# Generated by Django 3.0.1 on 2021-03-03 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_cancelledapproval_refund_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancelledapproval',
            name='refund_amount',
        ),
    ]
