# Generated by Django 3.0.1 on 2021-03-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_body',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='email_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='email',
            name='email_recipients',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='email_sender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='email_subject',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
