# Generated by Django 3.0.1 on 2021-03-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210304_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_body',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
