# Generated by Django 3.0.1 on 2021-03-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20210304_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_body',
            field=models.TextField(null=True),
        ),
    ]
