# Generated by Django 3.0.1 on 2021-03-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20210305_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_recipients',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='email_sender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
