# Generated by Django 3.0.1 on 2021-03-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20210305_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('discount_id', models.IntegerField(primary_key=True, serialize=False)),
                ('discount_start', models.IntegerField()),
                ('discount_end', models.IntegerField()),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
