# Generated by Django 3.0.1 on 2021-03-01 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.SalesExecutive')),
            ],
        ),
    ]
